color/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login/', views.login_user, name="login_user"),
    path('register/', views.regsiter_user, name="register_user"),
    path('about-us/', views.about, name="about_us"),
    path('collaborate/', views.collaborate, name="collaborate"),
    path('membership/', views.membership, name="membership"),
    path('product/<int:id>/', views.product_details, name="product-details"),
    path('search/<str:cat>/<int:id>', views.search, name="search"),
    path('my-designs/',views.my_designs, name='my-designs'),
    path('my-products/',views.user_products, name='my-products'),
    path('my-commission/',views.user_commission, name='my-commission'),
    path('upload-design/', views.upload_design, name="upload-design"),
    path('my-profile/', views.my_profile, name="my-profile"),
    path('my-wish-list/', views.wish_list, name="wish-list"),
    path('view-cart/', views.view_cart, name="view-cart"),
    path('order-summary/', views.order_summary, name="order-summary"),
    path('edit-address/<int:id>/', views.edit_address, name="edit-address"),
    path('designs-by/<int:id>/', views.user_design, name="user-design"),
]

colorcult/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include(('color.urls', 'color'), namespace="color")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

color/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, EmailValidator, validate_slug, URLValidator

# Create your models here.
class User(AbstractUser):
    gender = models.CharField(max_length=50, default="male")
    is_creator = models.BooleanField(default=False,null=True)
    phone_regex = RegexValidator(regex=r'^\d{10,10}$', message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=10, blank=True)

    class Meta:
        ordering = ['id']

class Banner(models.Model):
    img_height = models.PositiveIntegerField(default=330)
    img_width = models.PositiveIntegerField(default=330)
    first_image = models.ImageField( upload_to='banner/image/', height_field='img_height', width_field='img_width', max_length=None, blank=False)
    second_image = models.ImageField( upload_to='banner/image/',height_field='img_height', width_field='img_width', max_length=None,  blank=False)
    third_image = models.ImageField( upload_to='banner/image/', height_field='img_height', width_field='img_width', max_length=None, blank=False)
    long_banner_image = models.ImageField( upload_to='banner/image/', height_field='img_height', width_field='img_width', max_length=None, blank=False)

    def __str__(self):
        return str(self.first_image)
    
    class Meta:
        verbose_name = "Banner"
        verbose_name_plural = "Banners"
        ordering = ['id']
    
class HomeBanner(models.Model):
    banner_one = models.ImageField( upload_to='banner/image/', blank=False)
    banner_two = models.ImageField( upload_to='banner/image/', blank=False)
    banner_three = models.ImageField( upload_to='banner/image/', blank=False)
    banner_four = models.ImageField( upload_to='banner/image/', blank=False)
    

    class Meta:
        verbose_name = "HomeBanner"
        verbose_name_plural = "HomeBanners"
        ordering =['id']

    def __str__(self):
        return str(self.id)

class Theme(models.Model):
    theme = models.CharField( max_length=100) 
    date = models.DateTimeField( auto_now=True)
    theme_image = models.FileField( upload_to='product/image/',default="/media/image/temple.png", blank=False)
    class Meta:
        verbose_name = "Theme"
        verbose_name_plural = "Themes"
        ordering = ['id', 'theme', 'date']

    def __str__(self):
        return self.theme

class ThemeCategory(models.Model):
    theme = models.ManyToManyField("Theme", verbose_name="theme_category")
    category = models.CharField( max_length=100)
    date = models.DateTimeField( auto_now=True)
    category_image = models.FileField( upload_to='product/image/',default="/media/image/temple.png", blank=False)
    class Meta:
        verbose_name = "ThemeCategory"
        verbose_name_plural = "ThemeCategorys"
        ordering = [ 'id', 'category', 'date']

    def __str__(self):
        return self.category

class Product(models.Model):
    product_name = models.CharField( max_length=100, default="PUBG Grey T-shirt")
    creator = models.ForeignKey("User", verbose_name="Creator", on_delete=models.CASCADE)
    product_theme = models.ManyToManyField("Theme", verbose_name="Product Theme",  blank=True)
    prodcut_description = models.TextField()
    price = models.PositiveIntegerField()
    cult_member_price = models.PositiveIntegerField()
    product_image = models.FileField( upload_to='product/image/',default="/media/image/temple.png", blank=False)
    product_category = models.ManyToManyField("ThemeCategory", verbose_name="Product Theme Category",  blank=True)
    product_size = models.ManyToManyField("ProductSize", verbose_name="Product Size",  blank=True)
    product_related_to_gender = models.ManyToManyField("Gender", verbose_name="Gender",  blank=True)
    product_page_size = models.ManyToManyField("PageSize", verbose_name="Product Page Size",  blank=True)
    product_frame_size = models.ManyToManyField("FrameSize", verbose_name="Product Frame Size",  blank=True)
    product_color = models.ManyToManyField("Color", verbose_name="Add Hex code only for product")
    date = models.DateTimeField( auto_now=True)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Product"
        ordering = [ 'id', 'price', 'date']

    def __str__(self):
        return str(self.id)

class Color(models.Model):
    color = models.CharField(max_length=100)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "Color"
        verbose_name_plural = "Colors"

    def __str__(self):
        return str(self.color)


class ProductSize(models.Model):
    product_sizes = models.CharField( max_length=100)
    date = models.DateTimeField( auto_now=True)
    class Meta:
        verbose_name = "ProductSize"
        verbose_name_plural = "ProductSizes"
        ordering = [ 'id', 'date']


    def __str__(self):
        return str(self.product_sizes)

class Gender(models.Model):
    product_related_to_gender = models.CharField(max_length=50)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "Gender"
        verbose_name_plural = "Genders"
        ordering = [ 'id', 'date', 'product_related_to_gender']

    def __str__(self):
        return self.product_related_to_gender

class FrameSize(models.Model):
    size = models.CharField( max_length=50)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "FrameSize"
        verbose_name_plural = "FrameSizes"
        ordering = [ 'id', 'date', 'size']

    def __str__(self):
        return str(self.size)

class PageSize(models.Model):
    page_size = models.CharField(max_length=50)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "PageSize"
        verbose_name_plural = "PageSizes"
        ordering = [ 'id', 'date', 'page_size']

    def __str__(self):
        return self.page_size

class Image(models.Model):
    product_for = models.ForeignKey("Product", verbose_name="for_product_image", on_delete=models.CASCADE, default='/media/image/temple.png')
    product_images = models.ImageField( upload_to='product/image/')
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"
        ordering = [ 'id', 'date']

    def __str__(self):
        return str(self.id)


class Cart(models.Model):
    user = models.ForeignKey("User", verbose_name="User Cart", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", verbose_name="Product", on_delete=models.CASCADE)
    date = models.DateTimeField( auto_now=True)
    product_size = models.CharField( max_length=100, blank=True, null=True)
    product_color = models.CharField( max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = "Cart"
        verbose_name_plural = "Carts"

    def __str__(self):
        return str(self.user)
STATUS = [
    ('under_review', 'Under Review'),
    ('accepted', 'Accepted'),
    ('rejected', 'Rejected'),
]
class CreatorDesign(models.Model):
    user = models.ForeignKey("User", verbose_name="Creator User", on_delete=models.CASCADE)
    date = models.DateTimeField( auto_now=True)
    design_description = models.TextField()
    design_name = models.CharField(max_length=50, default="art")
    design_image = models.ImageField( upload_to='product/image/')
    design_status = models.CharField(choices=STATUS, max_length=50, default='under_review')

    class Meta:
        verbose_name = "CreatorDesign"
        verbose_name_plural = "CreatorDesigns"

    def __str__(self):
        return str(self.user)

class Address(models.Model):
    user = models.ForeignKey("User", verbose_name="User Address", on_delete=models.CASCADE)
    address = models.TextField()
    locality = models.CharField(max_length=100)
    landmark = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pin_code = models.CharField(max_length=10)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Address"

    def __str__(self):
        return str(self.user)

class Order(models.Model):
    user = models.ForeignKey("User", verbose_name="User Payment", on_delete=models.CASCADE)
    order_amount = models.IntegerField()
    razor_payment_id = models.CharField(max_length=10000)
    razor_order_id = models.CharField(max_length=10000)
    razor_signature = models.CharField(max_length=1000000)
    date = models.DateTimeField(auto_now=True)
    

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return str(self.user)

class Wishlist(models.Model):
    user = models.ForeignKey("User", verbose_name="User Wish list", on_delete=models.CASCADE)
    product_id = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now=True)
    

    class Meta:
        verbose_name = "Wishlist"
        verbose_name_plural = "Wishlists"

    def __str__(self):
        return str(self.product_id)

class Reviews(models.Model):
    date = models.DateTimeField(auto_now=True)
    review_for_product = models.ForeignKey("Product", verbose_name="Product Id", on_delete=models.CASCADE)
    review = models.CharField(max_length=150, help_text="Keep the review short and concise", verbose_name="Add your Review")
    rating = models.PositiveIntegerField()
    reviewer = models.ForeignKey("User", verbose_name="User who reviewed Product", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Reviews"
        verbose_name_plural = "Reviews"

    def __str__(self):
        return self.review

# PRODUCT_SIZES = [
#     ('-', 'Not Applicable'),
#     ('xs','XS'),
#     ('s','S'),
#     ('m','M'),

color/forms.py
from django import forms
from .models import Banner, User, CreatorDesign, Address
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator, RegexValidator
from django.forms import ModelForm

class RegisterUser(UserCreationForm):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(),label='Gender',) 
    is_creator = forms.BooleanField(label = 'Register as a creator', required=False)
    class Meta: 
        model = User 
        fields = ('phone_number', 'username', 'email', 'first_name', 'last_name', 'is_creator', 'gender') 

class UpdateProfile(forms.ModelForm):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(),label='Gender')
    class Meta:
        model = User
        fields = ('phone_number', 'username', 'email', 'first_name', 'last_name', 'gender') 

class CreatorDesignForm(forms.ModelForm):
    
    class Meta:
        model = CreatorDesign
        fields = ("design_description", "design_name", "design_image")
 
class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ("address","locality", "landmark", "city", "state", "pin_code")

class CollaborateForm(forms.Form):
    full_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    phone_regex = RegexValidator(regex=r'^\d{10,10}$', message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.")
    phone_number = forms.CharField(validators=[phone_regex], max_length=10,required=True)
    username = forms.CharField( max_length=50, required=True)
    design_file = forms.FileField( required=True)
    design_desc = forms.CharField( widget=forms.Textarea(), required=False)
    design_name = forms.CharField( required=True)

    

color/templates/pages/cart.html
{% extends '../base.html' %}
{% block title %}Color Cult | Shopping Cart{% endblock title %}
{% block content %}
<div class="container">
    <h3 class="head-line-text pos-rel">Shopping Cart</h3>
    <div class="row">
        <div class="col-md-6">
            <span class="items-count">Items( {{ product_count_in_cart }} )</span>
            <span class="sub">Subtotal</span>
        </div>
    </div>
    
    {% if product_object_list %}
        <div class="row">
            <div class="col-md-7">
                <ul class="ul cart-ul">
                    {% for p in product_object_list %}
                    
                        <li>
                            <div class="li-inner">
                                <div class="left-img">
                                    <img class="img-fluid" src="/media/{{ p.product_image }}">
                                </div>
                                <div class="right-text">
                                    <p class="name">{{ p.product_name }}</p>
                                    <p class="category">{{ p.product_category.first | join:', ' }}</p>
                                    <div class="p-list">
                                        <p>Color: <span>{{ p.product_color.first | join:', ' }}</span></p>
                                        <p>Size:<span></span></p>
                                        <p>Quantity:<span></span></p>
                                    </div>
                                    <div class="r-total">
                                        <span>
                                            <form method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="prod-value" value="{{ p.id }}">
                                                <button name="remove" id="remove" class="remove" type="submit">Remove</button>
                                            </form>
                                        </span>
                                        <span>Rs. {{ p.price }}</span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {%endfor%}
                </ul>
            </div>
            <div class="col-md-5">
                <div class="summary-box">
                    <p>Order Summary</p>
                    <ul class="ul summary-listing">
                        <li><span>Cart Total</span><span>₹ {{ cart_total }}</span></li>
                        <li><span>GST</span><span>₹ {{ gst }}</span></li>
                        <li><span>Total Amount</span><span>₹ {{ whole_total }}</span></li>
                        <li class="li-border"><span>Shipping Charges</span><span class="free">{% if shipping == "Free" %}{{ shipping }}{% else %}₹ {{ shipping }}{% endif %}</span></li>
                        <li><span class="total-pay">Total Payable</span><span>₹ {{ whole_total }}</span></li>
                    </ul>
                    
                </div>
                {% if request.user.is_authenticated %}
                    <a class="checkout" href="{% url 'color:order-summary' %}">Continue</a>
                {% else %}
                    <a class="checkout" href="{% url 'login' %}?next={{request.path}}">Continue</a>
                {% endif %}
            </div>
        </div>
     {% else %}
        <div class="">
            <p>You havn't shoped yet</p>
            <a href="{% url 'color:dashboard' %}">Go to shop</a>
        </div>
     {% endif %}
</div>
<div class="messages">
    {%if messages %}
        {%for message in messages%}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {%endfor%}
    {%endif%}
</div>
{% endblock %}

color/templates/pages/design-upload.html
{% extends '../base.html' %}
{% block title %}Upload Your Design{% endblock title %}
{% block content %}
{% load static %}
    <div class="container">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <h3 class="upload">Upload</h3>
            <div class="col-md-4 pos-rel">
                <div class="text-img-wrap">
                    <img src="{% static '/img/upload-ask.jpeg' %}" class="img-fluid">
                    <p> We would like you to visit our <a class="submission" href="#">Submission Guidelines</a>for more information.</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="design-upload">
                    <form method="POST" enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form}}
                        <button id="upload-submit"class="upload-submit" type="submit">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

color/templates/pages/search.html
{% extends '../base.html' %}
{% block title %} Product Details | ColorCult {% endblock title %}
{% block content %}
        <section id="home-banner">
        <div class="home-banner-slider">
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_one.url }}">
            </div>
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_two.url }}">
            </div>
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_three.url }}">
            </div>
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_four.url }}">
            </div>
        </div>
        </section>
        <section id="product-search">
            <div class="row">
                <div class="col-md-2">
                    <div class="search-left">
                    <p>Products</p>
                        <ul class="search-ui ul">
                            {% for get_all_theme_category in get_all_theme_categories %}
                                <li><a href="{% url 'color:search'  get_all_theme_category.category get_all_theme_category.id %}">{{ get_all_theme_category.category }}</a></li>
                            {% endfor %}
                        </ul>
                        <p>Popular Themes</p>
                        <ul class="theme-ul ul">
                            {% for get_all_theme in get_all_themes %}
                                <li><a href="{% url 'color:search'  get_all_theme.theme get_all_theme.id %}">{{ get_all_theme.theme }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="search-right">
                        <h2>{{ category_or_theme }}</h2>
                        <div class="breadcrumb">
                            <a href="{% url 'color:dashboard' %}">home</a>/
                            <a class="active-cat">{{ category_or_theme }}</a>
                        </div>
                        <div class="row mb-4">
                            {% for product in get_products_by_category_or_theme %}
                                <div class="col-md-3">
                                    <div class="prod-outer-wrap">
                                    <a class="prod-a" href="{% url 'color:product-details' product.id %}">
                                        <div class="prod-img-wrap">
                                        <img src="{{ product.product_image.url }}" alt="{{ product.prodcut_description }}" class="img-fluid h-100">
                                        </div>
                                        <div class="prod-text">
                                        <div class="prod-cat"> {{ product.product_theme.first}} </div>
                                        <div class="prod-theme"> {{ product.product_category.first }} </div>
                                        </div>
                                        <div class="pricing">
                                        <div class="normal-price">Rs. {{ product.price }} </div>
                                        <div class="cult-price"><span>Rs. {{ product.cult_member_price }}</span> for Cult memebers</div>
                                        </div>
                                    </a>
                                    <div class="design-by"> Design by <a class="creator" href="{% url 'color:user-design' product.creator.id %}">{{ product.creator }}</a></div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="pagination">
                            <span class="step-links">
                             <ul class="pagination justify-content-center">
                                {% if get_products_by_category_or_theme.has_previous %}
                                   <li> <a href="?page={{ get_products_by_category_or_theme.previous_page_number }}"class="page-link">Previous</a></li>
                                {% endif %}
                                {% if get_products_by_category_or_theme.has_next %}
                                    <span class="current">
                                        <li><a class="active">{{ get_products_by_category_or_theme.number }}</a></li>
                                    </span>
                                    <li> <a href="?page={{ get_products_by_category_or_theme.next_page_number }}"class="page-link">{{ get_products_by_category_or_theme.next_page_number }}</a></li>
                                {% endif %}
                                {% if get_products_by_category_or_theme.has_next %}
                                    <li><a href="?page={{ get_products_by_category_or_theme.next_page_number }}"class="page-link">Next</a></li>
                                {% endif %}
                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="your-design" class="search-design"></section>
{% endblock %}

color/templates/pages/user-commission.html
{% extends '../base.html' %}
{% block title %}Color Cult | My Commission{% endblock title %}
{% block content %}
<div class="container">
    <h3>My Commission</h3>
</div>
{% endblock %}

color/templates/pages/user-design-listing.html
{% extends '../base.html' %}
{% block title %} Product Details | ColorCult {% endblock title %}
{% block content %}
        <section id="home-banner">
        <div class="home-banner-slider">
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_one.url }}">
            </div>
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_two.url }}">
            </div>
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_three.url }}">
            </div>
            <div class="home-img">
            <img class="img-fluid" src="{{ get_home_banners.banner_four.url }}">
            </div>
        </div>
        </section>
        <section id="product-search">
            <div class="row">
                <div class="col-md-2">
                    <div class="search-left">
                    <p>Products</p>
                        <ul class="search-ui ul">
                            {% for get_all_theme_category in get_all_theme_categories %}
                                <li><a href="{% url 'color:search'  get_all_theme_category.category get_all_theme_category.id %}">{{ get_all_theme_category.category }}</a></li>
                            {% endfor %}
                        </ul>
                        <p>Popular Themes</p>
                        <ul class="theme-ul ul">
                            {% for get_all_theme in get_all_themes %}
                                <li><a href="{% url 'color:search'  get_all_theme.theme get_all_theme.id %}">{{ get_all_theme.theme }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="search-right">
                        <h2>{{ creator }}</h2>
                        <div class="row mb-4">
                            {% for product in get_products_by_user %}
                                <div class="col-md-3">
                                    <div class="prod-outer-wrap">
                                    <a class="prod-a" href="{% url 'color:product-details' product.id %}">
                                        <div class="prod-img-wrap">
                                        <img src="{{ product.product_image.url }}" alt="{{ product.prodcut_description }}" class="img-fluid h-100">
                                        </div>
                                        <div class="prod-text">
                                        <div class="prod-cat"> {{ product.product_theme.first}} </div>
                                        <div class="prod-theme"> {{ product.product_category.first }} </div>
                                        </div>
                                        <div class="pricing">
                                        <div class="normal-price">Rs. {{ product.price }} </div>
                                        <div class="cult-price"><span>Rs. {{ product.cult_member_price }}</span> for Cult memebers</div>
                                        </div>
                                    </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="pagination">
                            <span class="step-links">
                             <ul class="pagination justify-content-center">
                                {% if get_products_by_category_or_theme.has_previous %}
                                   <li> <a href="?page={{ get_products_by_category_or_theme.previous_page_number }}"class="page-link">Previous</a></li>
                                {% endif %}
                                {% if get_products_by_category_or_theme.has_next %}
                                    <span class="current">
                                        <li><a class="active">{{ get_products_by_category_or_theme.number }}</a></li>
                                    </span>
                                    <li> <a href="?page={{ get_products_by_category_or_theme.next_page_number }}"class="page-link">{{ get_products_by_category_or_theme.next_page_number }}</a></li>
                                {% endif %}
                                {% if get_products_by_category_or_theme.has_next %}
                                    <li><a href="?page={{ get_products_by_category_or_theme.next_page_number }}"class="page-link">Next</a></li>
                                {% endif %}
                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="your-design" class="search-design"></section>
{% endblock %}

color/templates/pages/user-designs.html
{% extends '../base.html' %}
{% block title %}My Designs{% endblock title %}
{% block content %}
<div class="container">
    <h3 class="head-line-text pos-rel">My Designs</h3>
    <div class="row mb-4">
        <div class="col-md-6">
            <p class="count-to">Total ({{ get_current_login_user_design_count }})
        </div>
         <div class="col-md-6 text-right">
            <a type="button" href="{% url 'color:upload-design' %}" class="btn btn-info upload-btn"><span>+</span> Upload</a>
        </div>
    </div>
    <div class="row">
        {% for get_current_login_user_design in get_current_login_user_designs %}
            <div class="col-md-3 designs-row">
                <div class="img-wrap">
                    <img src="{{ get_current_login_user_design.design_image.url }}" class="img-fluid">
                </div>
                <div class="text-wrap">
                    <h4 class="design-name">{{ get_current_login_user_design.design_name }}</h4>
                    <p class="design-status">Status:
                        {% if  get_current_login_user_design.get_design_status_display == "Under Review" %}
                            <span class="under-review pos-rel">{{ get_current_login_user_design.get_design_status_display }}</span>
                        {% elif  get_current_login_user_design.get_design_status_display == "Rejected" %}
                            <span class="rejected pos-rel">{{ get_current_login_user_design.get_design_status_display }}</span>
                        {% else %}
                            <span class="accepted pos-rel">{{ get_current_login_user_design.get_design_status_display }}</span>
                        {% endif %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}